---
title: "Rhadoop"
author: "김민우"
date: "Project"
output:
  prettydoc::html_pretty:
 theme: leonids
 toc : true
 #toc_float : true
 highlight: github
header-includes:
 - \usepackage{kotex}
 - \usepackage{subfig}
urlcolor : blue
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, webgl=TRUE, message=FALSE, warning=FALSE, fig.show='hold')
```

```{r}
library(dplyr)
library(ggplot2)
library(tidyverse)
library(lubridate)
library(patchwork)
```


# Load files
```{r}
files <- read.csv("formine.csv")
```


# select rate code 1 (정상)
# 필요 변수만 선택
```{r}
taxiCode1 <- files[which(files$rate_code == 1), ]
taxiCode1Simple <- taxiCode1 %>% select(trip_time_in_secs, trip_distance, total_amount)
```

# 거리 순 데이터 정렬
```{r}
# taxiCode1Simple <- arrange(taxiCode1Simple, trip_distance)
```

# 센터값 임의 지정 후 kmeans
```{r}
# centers (trip_distance)
# 1.46, 4.44, 10.85
centroid <- matrix(c(431.13969, 1.4554913, 9.047254,
                     1221.74895,4.3717573,20.888515,
                     2816.79566, 11.0882098, 46.766944), nrow=3, ncol=3, byrow=T)


kmeansRes <- kmeans(taxiCode1Simple, centers = centroid, iter.max=10, nstart=10)
kmeansRes$centers

# center를 직접 지정할 필요는 크게 없어보인다. 결과가 크게 달라지지 않는다
# 그래도 연산량 감소를 위해 센터를 직접 지정해주는 것이 정신에 이롭다.
```


# Plotting
```{r}
library(plotly)

taxiWithGroup <- taxiCode1 %>% mutate(cluster = factor(kmeansRes$cluster))



p <- plot_ly(taxiWithGroup, x=~trip_distance, y=~trip_time_in_secs, 
             z=~total_amount, color=~cluster) %>%
  add_markers(size=0.3)
print(p)
```


# cluster 별로 나눔 (회귀분석 용)
```{r}
taxiG1 <- taxiWithGroup[which(taxiWithGroup$cluster == 1), ] %>% select(-cluster) 
taxiG2 <- taxiWithGroup[which(taxiWithGroup$cluster == 2), ] %>% select(-cluster) 
taxiG3 <- taxiWithGroup[which(taxiWithGroup$cluster == 3), ] %>% select(-cluster) 
```

```{r}
# rm(taxiWithGroup)
# rm(taxiCode1Simple)
# rm(kmeansRes)
# rm(centroid)
# taxiWithGroup <- bind_rows(taxiG1, taxiG2, taxiG3)
# 변수가 지워지면 안되겠다. 추후 분석시 다른 변수로 이상치 원인을 찾아야하니까.
```


# 회귀분석 실시
```{r}
lmG1 <- lm(total_amount ~ trip_distance + trip_time_in_secs, data = taxiG1)
summary(lmG1)
lmG2 <- lm(total_amount ~ trip_distance + trip_time_in_secs, data = taxiG2)
summary(lmG2)
lmG3 <- lm(total_amount ~ trip_distance + trip_time_in_secs, data = taxiG3)
summary(lmG3)
```



# 잔차가 큰 값 선택 (양수인것만 = 정상값(추정값평균)보다 많이 나온 것)
# 잔차 갯수 기준은 클러스터 별 데이터 수가 다르므로 상위 0.1%로 한다.
```{r}
BigRes <- lmG1$residuals %>% sort(decreasing = T) %>% names()

BigResIDX <- BigRes[1:ceiling(length(BigRes)*0.001)]

taxiG1[BigResIDX,] %>% mutate(estimateFare = lmG1$fitted.values[BigResIDX], residual = lmG1$residuals[BigResIDX]) %>% select(total_amount, estimateFare, residual) %>% head()
taxiG1[BigResIDX,] %>% mutate(estimateFare = lmG1$fitted.values[BigResIDX], residual = lmG1$residuals[BigResIDX]) %>% select(total_amount, estimateFare, residual) %>% tail()
```

```{r}
# 조심해야 할 일
# 우리가 뽑은 이상치 데이터들이 진짜 덤티기가 아니라 입력 오류인 경우. (배제해야 됨)
# 진짜 그럴듯한 이유를 찾아야 함.
# Hyphothesis list
# 변수별 가설
  # VendorID : 특정 업체에서 유독 많다
  # hacklicense : 특정 기사가 많다던지
  # datetime : 특정시간대인지
  # Passenger count : 특정 승객수인지
  # Pickup location : 특정 승차 위치인지
  # Store and fwd flag : 저장을 일부러 안했는지
  # Dropoff location : 특정 하차 위치인지
  # Payment type : 특정 지불 방식인지
  # Extra : 특정 이유없는 과금인지?
  # TIp amount : 팁이 비싼지?
  # new variable - km/h : 특정 속도인지
# 임의의 우리가 세운가설
  # e.g. 여행객일 것이다. -> 위의 변수들을 어떻게 잘 사용할 것인지.
```

```{r}
# 변수가 다 있는 분포에서 살펴보자
# rm(lmG1, lmG2, lmG3)
selectedDataG1 <- taxiG1[BigResIDX, ]

selectedDataG1 %>% glimpse()
selectedDataG1 %>% head()
```

```{r}
# VendorID : 특정 업체에서 유독 많다
selectedDataG1 %>% select(vendor_id) %>% table()
nOfObs <- selectedDataG1 %>% group_by(vendor_id) %>% summarize(count = n())

ggplot(nOfObs,
       aes(x = as.factor(vendor_id), y = count, fill = vendor_id)) + 
  geom_bar(stat = "identity") + 
  labs(x = "vendor ID",
       y = "count",
       title = "vendor ID",
       subtitle = "rate code 1, short distance") +
  geom_text(aes(label = count), vjust=0) +
  theme_bw()

# 큰 차이 없다
```

```{r}
# hacklicense : 덤티기를 씌우는 기사들의 덤티기 총금액 비율과 횟수 

BadDrivers <- selectedDataG1 %>% select(hack_license, total_amount) %>% mutate(estimateFare = lmG1$fitted.values[BigResIDX]) %>% group_by(hack_license) %>% summarize(totalSum = sum(total_amount), estimateSum = sum(estimateFare), count = n()) %>% mutate(ratio = totalSum/estimateSum) %>% arrange(desc(count))

BadDrivers
BadDrivers %>% arrange(desc(ratio))
taxiG1 %>% glimpse()
```

```{r}
# hacklicense : BadDrivers + 총 카운트
allDrivingFreqG1 <- taxiG1 %>% select(hack_license) %>% group_by(hack_license) %>% summarize(count = n())
bigResDrivingFreaG1 <- selectedDataG1 %>% select(hack_license) %>% group_by(hack_license) %>% summarize(count=n())
allDrivingFreqG1 %>% dim()
bigResDrivingFreaG1 %>% dim()
count <- inner_join(allDrivingFreqG1, bigResDrivingFreaG1, by = "hack_license", suffix = c("All", "Outlier")) %>% arrange(desc(countOutlier))
BadDriversDone <- bind_cols(BadDrivers, count[,"countAll"])[, c("hack_license","totalSum", "estimateSum", "ratio", "count", "countAll")]
BadDriversDone %>% arrange(desc(ratio))

pivotBadDrivers <- BadDriversDone %>% select(hack_license, totalSum, estimateSum, ratio) %>% arrange(desc(ratio)) %>% head(10) %>% select(-ratio) %>% pivot_longer(cols = !hack_license, names_to = "sumType", values_to = "value")

ggplot(pivotBadDrivers, aes(x = hack_license, y = value, fill = sumType)) +
  geom_col(position = "dodge") + theme(axis.text.x = element_blank()) + labs(title = "Top 10 billing rate")
```

```{r}
# datetime : 특정시간대인지
pickupHourG1 <- hour(selectedDataG1$pickup_datetime) %>% table() %>% as.data.frame()
names(pickupHourG1) <- c("Hour", "count")

dropoffHourG1 <- hour(selectedDataG1$dropoff_datetime) %>% table() %>% as.data.frame()
names(dropoffHourG1) <- c("Hour", "count")

hourG1 <- inner_join(pickupHourG1, dropoffHourG1, by="Hour", suffix = c("Pickup","Dropoff"))
hourG1 <- hourG1 %>% pivot_longer(cols = !Hour, names_to = "hourType", values_to = "value")
# Change line colors by groups
ggplot(hourG1, aes(x=Hour, y=value, group=hourType)) +
  geom_line(aes(color=hourType), size = 1)+
  geom_point(aes(color=hourType), size = 2)

# 이상치라고 판단한 약 5000개의 데이터에 대해 시간의 분포를 살펴봄.
# 주로 새벽시간대나 저녁 이후 시간대에 이상치 데이터들이 포진돼있음.
# 이것이 덤티기인지, 야간 할증인지는 잠재변수로 고려해봐야 하지만,
# 우리가 가지고 있는 데이터로는 이를 판단해볼 수 없음. (Extra 변수가 없기 때문.)
```

```{r}
# Passenger count : 특정 승객수인지
NofObs <- selectedDataG1 %>% group_by(passenger_count) %>% summarize(count=n())


ggplot(NofObs,
       aes(x = as.factor(passenger_count), y = count, fill = as.factor(passenger_count))) + 
  geom_bar(stat = "identity") + 
  labs(x = "passenger count",
       y = "count",
       title = "passenger count",
       fill = "passenger count") +
  geom_text(aes(label = count), vjust=0) +
  theme_bw()
# 1명일때가 많다.
```


```{r}
g1 <- selectedDataG1 %>% ggplot(aes(x = pickup_longitude, y = pickup_latitude)) +
  geom_hex(bins=100) +
  scale_fill_continuous(type = "viridis") +
  labs(title = "승차 경도 및 위도") +
  theme_bw()

g2 <- selectedDataG1 %>% ggplot(aes(x = dropoff_longitude, y = dropoff_latitude)) +
  geom_hex(bins=100) +
  scale_fill_continuous(type = "viridis") +
  labs(title = "하차 경도 및 위도") +
  theme_bw()

g1 + g2



library(ggmap)
ggmap::register_google(key = "AIzaSyB1DnL49hsPQyix6DnhnIMb2OUpc617_4k")
ggmap::has_google_key()

NYMAP <- ggmap::get_map("New York, NY, USA", maptype = "terrain")

g3 <- ggmap(NYMAP) + geom_point(data = selectedDataG1, 
                              aes(x = pickup_longitude, y = pickup_latitude), size =.003, alpha =.01) +
  labs(title = "Taxi PickUp location")
g3

g4 <- ggmap(NYMAP) + geom_point(data = selectedDataG1, 
                              aes(x = dropoff_longitude, y = dropoff_latitude), size =.003, alpha=.01) +
  labs(title = "Taxi dropoff location")
g4

g3 + g4



# 밀집된 위경도

# (1)
# 40.77411263879798, -73.87177711031461
# East Elmhurst (지역)
# 뉴욕 라과디아 공항 + 몇 유명 호텔


# (2)
# 40.778186, -73.925555
# 관광명소
# kenedy bridge + 에스토리아 공원


# (3)
# 40.7489662320195, -73.98564147146332
# 관광명소
# 엠파이어 스테이트 빌딩

# (4)
#  40.77995075048802, -73.96316396457098
# 관광명소
# 메트로폴리탄 미술관, 솔로몬 R, 구겐하임 미술관, 센트럴파크


# (5)
# 40.81007194617472, -73.95006688207894
# 관광명소
# 아폴로 영화관, 알로프트 할렘, 마르쿠스 가비공원
```

```{r}
# Payment type : 특정 지불 방식인지
NofObs <- selectedDataG1 %>% group_by(payment_type) %>% summarize(count=n())


ggplot(NofObs,
       aes(x = as.factor(payment_type), y = count, fill = as.factor(payment_type))) + 
  geom_bar(stat = "identity") + 
  labs(x = "payment type",
       y = "count",
       title = "payment type",
       fill = "payment type") +
  geom_text(aes(label = count), vjust=0) +
  theme_bw()

# 대부분이 카드 데이터에 있다.
# 아마 현금으로 결제한 덤티기에 대해서는 입력을 기사가 일부러 안할 수도 있다 -> 가정
```

```{r}
# TIp amount : 팁이 비싼지?
library(skimr)
selectedDataG1[-which(selectedDataG1$tip_amount == 0),] %>% mutate(tipratio = tip_amount / total_amount) %>% select(tipratio) %>% skim()


# cluster 1 (전체데이터) 에서 팁의 비율 (=일반적인 팁의 비율, 약 15%)
taxiG1[-which(taxiG1$tip_amount == 0),] %>% mutate(tipratio = tip_amount / total_amount) %>% select(tipratio) %>% skim()

# 전체 데이터에서의 tip Ratio가 15%인데, 이상치로 판별된 데이터 셋의 tip Ratio는 15%보다 한참 큰 34.3% 이다(평균, tip=0 제외).
# total amount에는 tip이 포함되지 않았음에도 불구하고.
# 미터기 금액도 많이 내고, 팁도 많이 내고
```






